spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    dirverClassName: org.mysql.Driver
    username: root
    password: dnjswhdals1@

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/mapper/*.xml
