spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    dirverClassName: org.mysql.Driver
    username: root
    password: dnjswhdals1@
