spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  profiles:
    active: db_config

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: wonjjong.mybatisExample.hello.member.vo
  mapper-locations: mybatis/mapper/*.xml
